version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq-healthcore-docker
    ports:
      - "5673:5672"     # AMQP
      - "15673:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: 123456
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network-notification-service

  app-notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-notification-service
    ports:
      - "8081:8081"
      - "5006:5006"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LANG=pt_BR.UTF-8
      - LANGUAGE=pt_BR:pt
      - LC_ALL=pt_BR.UTF-8
      - JAVA_TOOL_OPTIONS= "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network-notification-service
networks:
  app-network-notification-service: