@startuml
title HealthCore - Fluxo Principal de Operações com Mensageria

actor Usuario
participant AppointmentController
participant AppointmentService
participant AppointmentProducer
queue RabbitMQ
participant AppointmentConsumer
'participant NotificationService


== Agendamento de Consulta ==
Usuario -> AppointmentController: POST /appointments
activate AppointmentController
AppointmentController -> AppointmentService: criarAgendamento(dados)
activate AppointmentService
AppointmentService -> AppointmentProducer: enviarEventoAgendamento()
activate AppointmentProducer
AppointmentProducer -> RabbitMQ: publish(evento)
RabbitMQ -> AppointmentConsumer: deliver(evento)
deactivate AppointmentProducer
'AppointmentService --> AppointmentController: resposta agendamento
'AppointmentController --> Usuario: confirmação

deactivate AppointmentService

deactivate AppointmentController

== Consumo de Evento de Notificação ==
'RabbitMQ -> NotificationConsumer: consume(evento)
'activate NotificationConsumer
'NotificationConsumer -> NotificationService: processarEvento(evento)
'activate NotificationService


'NotificationService --> NotificationConsumer: ok
'NotificationConsumer --> RabbitMQ: ack

'deactivate NotificationService

'deactivate NotificationConsumer

@enduml

