version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: container_postgres_healthcore
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: healthcore
    ports:
      - "5433:5432"
    volumes:
      - healthcore_dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 15s
      retries: 3
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: appuser
      RABBITMQ_DEFAULT_PASS: appsecret
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app-healthcore:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-healthcore
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LANG=pt_BR.UTF-8
      - LANGUAGE=pt_BR:pt
      - LC_ALL=pt_BR.UTF-8
      - JAVA_TOOL_OPTIONS= "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

volumes:
  healthcore_dbdata:

networks:
  app-network: